[theme]
base = "dark"
primaryColor = "#ccff00"
backgroundColor = "#080c09"
secondaryBackgroundColor = "#111612"
textColor = "#F8FAFC"
font = "sans serif"

[browser]
gatherUsageStats = false

[server]
headless = true

